// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Atdgen_codec_runtime = require("@ahrefs/bs-atdgen-codec-runtime/src/atdgen_codec_runtime.bs.js");

Atdgen_codec_runtime.Decode[/* option_as_constr */25](Atdgen_codec_runtime.Decode[/* int */4]);

var partial_arg = Atdgen_codec_runtime.Encode[/* int */5];

var partial_arg$1 = Atdgen_codec_runtime.Encode[/* array */9];

function write__1(param) {
  return partial_arg$1(partial_arg, param);
}

var partial_arg$2 = Atdgen_codec_runtime.Decode[/* int */4];

var partial_arg$3 = Atdgen_codec_runtime.Decode[/* array */12];

function read__1(param) {
  return partial_arg$3(partial_arg$2, param);
}

var write_example = Atdgen_codec_runtime.Encode[/* make */0]((function (t) {
        return Atdgen_codec_runtime.Encode[/* obj */14](/* :: */[
                    Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "text", t[/* text */0]),
                    /* :: */[
                      Atdgen_codec_runtime.Encode[/* field */12](undefined, write__1, "numbers", t[/* numbers */1]),
                      /* :: */[
                        Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* int */5], "lives", t[/* lives */2]),
                        /* :: */[
                          Atdgen_codec_runtime.Encode[/* field_o */13](undefined, Atdgen_codec_runtime.Encode[/* int */5], "stuff", t[/* stuff */3]),
                          /* [] */0
                        ]
                      ]
                    ]
                  ]);
      }));

var read_example = Atdgen_codec_runtime.Decode[/* make */0]((function (json) {
        var partial_arg = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$1 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$2 = Atdgen_codec_runtime.Decode[/* field */15];
        return /* record */[
                /* text */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$1("text", partial_arg, param);
                      }), json),
                /* numbers */Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                        return partial_arg$2("numbers", read__1, param);
                      }), json),
                /* lives */Atdgen_codec_runtime.Decode[/* decode */1](Atdgen_codec_runtime.Decode[/* fieldDefault */16]("lives", 9, Atdgen_codec_runtime.Decode[/* int */4]), json),
                /* stuff */Atdgen_codec_runtime.Decode[/* decode */1](Atdgen_codec_runtime.Decode[/* fieldOptional */17]("stuff", Atdgen_codec_runtime.Decode[/* int */4]), json)
              ];
      }));

exports.read_example = read_example;
exports.write_example = write_example;
/*  Not a pure module */
