// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/src/Json.bs.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Int64 = require("bs-platform/lib/js/int64.js");
var Example_bs$AtdgenQuickstart = require("./example_bs.bs.js");

var example_001 = /* numbers : array */[
  1,
  2,
  3,
  4,
  5
];

var example_002 = /* level : int64 */[
  /* hi */2097152,
  /* lo */0
];

var example_004 = /* stuff */33;

var example = /* record */[
  /* text */"Hello there",
  example_001,
  example_002,
  /* lives */12,
  example_004
];

console.log("Record:", example);

console.log("JS:", Curry._1(Example_bs$AtdgenQuickstart.write_example, example));

var json = Json.parseOrRaise("{\"numbers\": [5,4,3], \"text\": \"string\", \"level\": \"9007199254740992\"}");

var record = Curry._1(Example_bs$AtdgenQuickstart.read_example, json);

console.log("Decoded record:", record);

console.log("Decoded level:", record[/* level */2]);

console.log("Decoded level (as string):", Int64.to_string(record[/* level */2]));

exports.example = example;
exports.json = json;
exports.record = record;
/*  Not a pure module */
